# This is a basic workflow to help you get started with Actions

name: Auto_Merge_Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Integration_Env_Run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Integration

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Integration Envirnoment Run No Protection Rule
        
  Prod_Env_Run:
    needs: Integration_Env_Run
    runs-on: ubuntu-latest
    environment: Production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Production Envirnoment Run -with Wait time of 1 min 
        
 
  Merge-branch:
    needs: Prod_Env_Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge Development -> Main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: Development
          target_branch: Main
          github_token: ${{ secrets.GITHUB_TOKEN }}
